### ISSUE TITLE
el capitan vs sublime vs processing

### ISSUE THREAD

**Issue by matthiasvv** [processing/processing#3784]
Hi, 

I noticed that i cant run processing in sublime on el capitan. 
After a bit of searching around i found out it was because processing can't install processing-java on the new el capitan. 

is there a fix for this ? 
please tell me how i can make it work.

kind regards

**Comment by benfry** [comment]
You heard wrong. That's already fixed in beta 5: https://github.com/processing/processing/issues/3497

**Comment by nelsonvassalo** [comment]
I still can't use it somehow. Running El Capitan GM and Sublime Text 3…

`[Errno 2] No such file or directory: 'processing-java'
[cmd: ['processing-java', '--force', '--sketch=/Users/nelsonvassalo/Desktop/nelson/build', '--output=/Users/nelsonvassalo/Desktop/nelson/build/build-tmp', '--run']]
[dir: /Users/nelsonvassalo/Desktop/nelson/build]
[path: /usr/bin:/bin:/usr/sbin:/sbin]`

**Comment by matthiasvv** [comment]
Same problem

**Comment by nelsonvassalo** [comment]
Any news? Is this a known problem or might be my responsibility?

**Comment by REAS** [comment]
@nelsonvassalo Please take this into the forum: http://forum.processing.org

**Comment by manuelsuarez** [comment]
Any news?

**Comment by bluefin88** [comment]
Currently it is still not working for me in the latest version of Processing 3.0.1 (23 October 2015).
