### ISSUE TITLE
Processing 3.0.2 Error

### ISSUE THREAD

**Issue by Futuremanzero** [processing/processing#4417]
Hello, I just got this error when trying to open 3.0.2 for the first time. Windows 10 64-bit.

![error](https://cloud.githubusercontent.com/assets/9246490/14676329/016f60b0-06db-11e6-9781-f06f7b9b0d17.jpg)

**Comment by Futuremanzero** [comment]
It might have been an issue with the install. Deleted and downloaded again and it's fine now.

**Comment by Futuremanzero** [comment]
I think I figured out what's happening. If the folder for processing 3.0.2 is on my desktop it will open and work but if I move it (or extract a new copy) into the folder where I organize previous versions of processing then I get this error. For now I'll run it off my desktop, but if anyone knows a solution so that I can move it and it will still work I would greatly appreciate it.

**Comment by JakubValtar** [comment]
Hi, thanks for the report.

Could you please post full file paths where it worked and where it didn't work?

**Comment by benfry** [comment]
That sounds like you're moving just Processing.exe to another location, not the entire folder. Is that the case? You have to keep the entire Processing folder intact, otherwise you'll see errors like this, which is happening because it cannot find its support files.

**Comment by Futuremanzero** [comment]
Hi all, the original path was:
C:\Users\Owner\Desktop

The problem appeared when I moved the processing-3.0.2 folder and its contents to a folder on the desktop where I've been keeping the folders with prior versions of processing to keep them organized. I tested 2.0 and 3.0b6 and both of those versions seem to work fine after moving them.  

I played around with it a bit and I renamed that folder from "Processing + Arduino" to "Processing Arduino" (dropped the plus) and now it seems to be working fine. Not sure if that's what caused it since the other versions didn't seem to have a problem with the folder name, but now its working.

Thanks!

**Comment by JakubValtar** [comment]
Thanks @Futuremanzero, there was a bug and paths with '+' characters were handled incorrectly. It's fixed in my PR and should be merged soon.

**Comment by itzikt** [comment]
Hi all !
problem not solved ! - I download today 'processing-3.0.2-windows64' - and the same problem that was describe by 'Futuremanzero' in the top of this issue occurs !  (in my case - I installed under folder named DCC++) 

Meanwhile , I found a bypass
 To solved the problem - Just validate that the extract of zip file will be done in a folder that** his full path name will not include the sign "+"**

**Comment by JakubValtar** [comment]
Hi @itzikt,

1) my pull request it not merged yet
2) it will be fixed in next release (3.0.3 or 3.1)

**Comment by itzikt** [comment]
Than's
no problem, meanwhile can use the bypass

**Comment by MattGarfield** [comment]
I've run into this issue with Processing 3.1.1 on a Windows 7 PC on a Domain network with Roaming Profiles. I've seen issue with other software packages having trouble with Roaming Profiles because the file path uses a '$' for redirection.  I'm not sure if the '$' is part of the problem here, but since the original issue was related to '+' in the file path, I think this is a good candidate. 

This is also a difficult issue to troubleshoot because there is a minority small subset of users with Processing 3.1.1 on Windows 7 on a Domain Network with Profile Redirection.

@JakubValtar Can you validate that the fix you employed for the '+' would have also handled '$' in the file path?

![processing error](https://cloud.githubusercontent.com/assets/9786463/17035363/e070b522-4f54-11e6-850e-271a5213d0ca.jpg)

**Comment by itzikt** [comment]
Dear Matt !

your fix is working.

Just finish to check it with variation file path name  (including  '+' /
'$' / '++' / '++$') and it's work perfect.


Thank's

Itzik

On 21 Jul 2016 22:08, "Matt Garfield" <notifications@github.com> wrote:
>
> I've run into this issue with Processing 3.1.1 on a Windows 7 PC on a
Domain network with Roaming Profiles. I've seen issue with other software
packages having trouble with Roaming Profiles because the file path uses a
'$' for redirection. I'm not sure if the '$' is part of the problem here,
but since the original issue was related to '+' in the file path, I think
this is a good candidate.
>
> This is also a difficult issue to troubleshoot because there is a
minority small subset of users with Processing 3.1.1 on Windows 7 on a
Domain Network with Profile Redirection.
>
> @JakubValtar Can you validate that the fix you employed for the '+' would
have also handled '$' in the file path?

**Comment by JakubValtar** [comment]
I built a small network from my laptops and the problem is caused by running from the network location. It handles $ properly so that's just a red herring. I'll investigate today and prepare a fix since now I can reproduce the issue.

**Comment by MattGarfield** [comment]
Ah, ok- thanks for digging in and identifying the true cause of the issue!

**Comment by benfry** [comment]
Fix now included for 3.1.2.

**Comment by MattGarfield** [comment]
Yesssss! Thank you!
