### ISSUE TITLE
fullScreen /w SPAN does not work on mac

### ISSUE THREAD

**Issue by digitalhoax** [processing/processing#4561]
The fullscreen, spanned window is displayed off screen. To reproduce load the
"LoadDisplayOBJ" example, change
`size(640, 360, P3D);`
to
`fullScreen(P3D, SPAN);`
and run. There is no window. When you go into mission control, the correctly sized window can be seen.

**Comment by benfry** [comment]
fullScreen(SPAN) was developed on a Mac. What details can you provide about your system/setup that might help us figure out why it's broken on your machine?

**Comment by digitalhoax** [comment]
I just tested this on a recent iMac, the bug is gone. On my MacBook Pro (Retina, 13-inch, Late 2013) the bug is present even in the latest version of Processing (3.1.2). On a colleagues MacBook, the same bug exists. 

OSX 10.11.6
MacBook Pro (Retina, 13-inch, Late 2013)
2,8 GHz Intel Core i7
16 GB 1600 MHz DDR3
Intel Iris 1536 MB


What kind of further details would you like to know?

**Comment by benfry** [comment]
Can you take a screenshot of the Displays Preferences window that shows the display layout (where monitor 1 and 2 are, where the menubar is)?

**Comment by digitalhoax** [comment]
Sure, here is a screenshot 
https://www.dropbox.com/s/lpelb95y4jydx1q/Screenshot%202016-08-09%2011.20.29.png?dl=0

And here is a video of what happens when I modify the example as described in my first post (latest processing 3.1.2, right screen recorded)
https://youtu.be/JnfC8PPw3Zo

**Comment by benfry** [comment]
Is “Displays Have Separate Spaces” checked on your machine? (And if so, is it fixed by unchecking it?)

<img width="780" alt="screen shot 2016-08-09 at 8 02 21 am" src="https://cloud.githubusercontent.com/assets/1623101/17515650/9e755b16-5e07-11e6-9018-19ccb4e95ac1.png">

**Comment by digitalhoax** [comment]
I unchecked it after I had processing tell me to do so when trying SPAN for the first time. So Unchecking did not fix the bug.

**Comment by benfry** [comment]
But you checked it again later? After unchecking it, you have to log out or restart your machine for it to work properly.

**Comment by digitalhoax** [comment]
No, it has been off ever since, with multiple reboots in between.

**Comment by mimiyin** [comment]
I am experiencing the same problem after upgrading from Yosemite to El Capitan. The problem only arises using P2D.

**Comment by benfry** [comment]
@mimiyin Ohhh... that's an important point. Thanks for reporting.

**Comment by codeanticode** [comment]
This might be due to something breaking in JOGL on El Capitan. I use the [setFullscreen](https://jogamp.org/deployment/jogamp-next/javadoc/jogl/javadoc/com/jogamp/newt/opengl/GLWindow.html#setFullscreen(java.util.List)) method in GLWindow:

https://github.com/processing/processing/blob/master/core/src/processing/opengl/PSurfaceJOGL.java#L403
