### ISSUE TITLE
Calling PShape.translate(), PShape.rotate() etc creates and stores a new PMatrix

### ISSUE THREAD

**Issue by hamoid** [processing/processing#5685]
I opened this issue because of a performance issue with Retained particles, but you can directly jump to my answer to see the actual issue.

## Description

Running the `DynamicParticlesRetained` often drops frames (high numbers, up to 15 frames late) on an Nvidia GTX 1060. Running the `DynamicParticlesImmediate` performs much better and shows no such issue.

## Expected Behavior

Retained is supposed to perform better than Immediate mode. Frames should not be dropped at that rate.

## Current Behavior

Frames are frequently dropped and the animation is full of jitter due to long pauses.

## Steps to Reproduce

To produce actual data and not just a subjective impression, I opened both `DynamicParticlesRetained` and `DynamicParticlesImmediate` and made the following changes:

```
// add this global
long lastTime;

// make sure the frameRate is 60 inside setup()
frameRate(60);

// insert these lines at the top of draw(), before background(0). 
// They will print the delay since the last frame in milliseconds 
// if it's above 20ms (at 60 fps the expected value is 16.666ms)
void draw () {
  long nuTime = System.nanoTime();
  float diff = (nuTime - lastTime) / 1000000.0;
  if(diff > 20) {
    println(diff, hour() + ":" + nf(minute(), 2) + ":" + nf(second(), 2));
  }
  lastTime = nuTime; 
  
  background(0);

// comment out
//     println("fps: " + frate);
```

Run each sketch for one minute leaving the mouse at the top border and observe the console.

### Immediate mode 

9 frames were shown as late (a few more were visible but not detected due to the 20ms threshold), subtle jitter (1 frame late).

```
1.6332468E7 19:44:58
50.23394 19:44:58
20.017307 19:44:59
26.053064 19:45:21
21.748043 19:45:40
25.529957 19:45:41
20.312368 19:45:43
20.26308 19:45:45
21.835554 19:45:47
20.920164 19:45:52
```

### Retained mode (many frames were late, visible hiccups)

52 frames were shown as late, with very visible pauses. 259 ms at 60fps is about 15 frames late.

```
1.6496129E7 19:47:42
104.17787 19:47:42
21.417135 19:47:42
198.30045 19:47:43
21.605522 19:47:44
30.506672 19:47:44
34.44974 19:47:46
49.50074 19:47:47
302.4965 19:47:48
29.086777 19:47:49
64.352455 19:47:49
221.59677 19:47:50
68.06031 19:47:51
63.470654 19:47:52
224.25464 19:47:53
69.465866 19:47:55
70.64256 19:47:56
21.7029 19:47:58
72.15584 19:47:58
259.8315 19:48:00
51.579815 19:48:01
67.42985 19:48:03
76.251785 19:48:04
88.897095 19:48:06
106.75623 19:48:07
257.9176 19:48:09
56.207336 19:48:10
70.09778 19:48:11
77.51151 19:48:12
67.30514 19:48:14
69.65708 19:48:15
79.876305 19:48:16
256.2453 19:48:18
46.30062 19:48:19
59.963913 19:48:20
89.71463 19:48:22
63.56876 19:48:23
242.00153 19:48:24
51.244728 19:48:26
61.695816 19:48:27
65.01016 19:48:29
22.264074 19:48:29
20.493372 19:48:29
70.53066 19:48:30
254.26923 19:48:32
54.74097 19:48:33
20.940067 19:48:34
78.707054 19:48:35
89.770195 19:48:36
68.60402 19:48:38
259.58456 19:48:40
21.321068 19:48:41
57.82642 19:48:41
```

Maybe I made some mistake in the numbers, but the difference between the two approaches is very noticeable by looking at the screen.

## Your Environment

Processing 3.4, Ubuntu 18.04, Zotac Magnus computer with 8Gb RAM (VR capable computer with a GTX 1060).

## Possible Causes / Solutions

I suspect this line (PShape.translate(...))

    part.translate(velocities[n].x, velocities[n].y);

which is only present in the retained mode example.

**Comment by hamoid** [comment]
Could the reason be that in https://github.com/processing/processing/blob/master/core/src/processing/opengl/PShapeOpenGL.java calls to `transform()` call `pushTransform()` (each time we would do translate, for instance) which creates a `new PMatrix3D` and adds it to `transformStack`, but those piling matrices are only removed once the user calls `resetMatrix`?

**Comment by PratiquesAlgorithmiques** [comment]
In the DynamicParticlesRetained example, if one sets npartTotal = 60000 if grinds to a halt in a few seconds on a fast graphics card...

**Comment by PratiquesAlgorithmiques** [comment]
Any hope of seeing this fixed ? If I can help I'd be happy to but not sure how.

**Comment by PratiquesAlgorithmiques** [comment]
anyone ???

**Comment by PratiquesAlgorithmiques** [comment]
Is it possible that this problem will be fixed sometime soon ? Thanks

**Comment by codeanticode** [comment]
@hamoid the creation of the PMatrix objects does indeed slow down the particle system, and their use can be actually removed by updating the inverse transformation at each step so no need to store the individual transformations in a matrix stack. By using this more efficient approach, there are much fewer dropped frames. This is the commit that implements this approach: https://github.com/processing/processing/commit/93bc3bd34031675176e15dd24ddf3116076388a3

**Comment by codeanticode** [comment]
There were several other fixes committed recently to the main branch, so I'd imagine that a new version will come out soon.

**Comment by PratiquesAlgorithmiques** [comment]
i just downloaded 3.5.2 but i still have the same bottleneck with shapes[i].translate where shapes.length = 62500 (cubes). it drops from 120fps to 16fps when i add  shapes[i].translate

shapes = thisModel.getChildren();

for (int i = 0; i < shapes.length; i++) {   
	shapes[i].resetMatrix();
	shapes[i].translate(m.x, m.y, m.z); 
}

shape(thisModel);

anyone for a fix ?
thanks

**Comment by codeanticode** [comment]
@PratiquesAlgorithmiques there is a limit to what you can do with PShape. It can greatly improve performance provided that the geometry remains unchanged, since it can then be copied to the GPU memory just one time. If you are modifying all the vertices in each frame, then this performance advantage is lost since Processing has to copy the modified geometry to the GPU every time. In that case, it might be faster to use immediate mode, this is, just regular drawing calls without PShape.

**Comment by PratiquesAlgorithmiques** [comment]
thanks for your response codeanticode ! in fact it is just 62500 cubes. i change their position every frame and occasionally their color with .setFill. But that is all. PShape should work for that no ? It worked great with GLGraphics.

**Comment by PratiquesAlgorithmiques** [comment]
thanks for looking into it because i've been trying to port my 151 + GLGraphics project for a long time !

**Comment by PratiquesAlgorithmiques** [comment]
I tried the 3.5.3 version but same bottleneck. 
it is definitely the shapes[i].translate line that slows everything way down.

for (int i = 0; i < shapes.length; i++) {
shapes[i].resetMatrix();
shapes[i].translate(m.x, m.y, m.z);
}
it is so frustrating because i don't know what to do to move forward. I absolutely need to port my very long 151 + GLGraphics program to P3 very soon. any suggestions, anyone ? help !

**Comment by neilcsmith-net** [comment]
Also check out https://discourse.processing.org/t/pshape-resetmatrix-not-resetting-rotation-in-p2d/8508 which suggests there might be some issues with this fix so far.

**Comment by PratiquesAlgorithmiques** [comment]
# neilcsmith-net I tried the matrix = new PMatrix3D(); trick but fps is the same ; (

**Comment by neilcsmith-net** [comment]
@PratiquesAlgorithmiques sorry, it wasn't intended as a suggestion for a workaround - more a heads up for @codeanticode that this appears to have also caused a regression somewhere.

**Comment by PratiquesAlgorithmiques** [comment]
ok thanks @neilcsmith-net

**Comment by PratiquesAlgorithmiques** [comment]
Still stuck with the same problem on version 3.5.4. Any chance you could look into it when you have time  @codeanticode ?
Thanks !
